openapi: 3.0.1
info:
  title: Remote Patient Monitoring System API
  description: 遠隔療養者モニタリングシステムのAPIです。
  termsOfService: http://swagger.io/terms/
  contact:
    email: hal@code4japan.org
  license:
    name: MIT License
    url: https://github.com/codeforjapan/remote-patient-monitoring-api/blob/main/LICENSE
  version: 1.0.0
servers:
  - url: /
paths:
  /api/admin/login:
    $ref: ./paths/admin/login.yaml
  /api/nurse/login:
    $ref: ./paths/nurse/login.yaml
  /api/patient/login:
    $ref: ./paths/patient/login.yaml
  /api/admin/center/:
    $ref: ./paths/admin/center.yaml
  /api/nurse/center/:
    $ref: ./paths/nurse/center.yaml
  /api/admin/center/{centerId}:
    $ref: ./paths/admin/center-by-id.yaml
  /api/nurse/center/{centerId}:
    $ref: ./paths/nurse/center-by-id.yaml
  /api/admin/center/{centerId}/nurse/:
    $ref: ./paths/admin/nurse-by-center-id.yaml
  /api/nurse/center/{centerId}/nurse/:
    $ref: ./paths/nurse/nurse-by-center-id.yaml
  /api/admin/nurse/{nurseId}:
    $ref: ./paths/admin/nurse-by-id.yaml
  /api/nurse/nurse/{nurseId}:
    $ref: ./paths/nurse/nurse-by-id.yaml
  /api/admin/center/{centerId}/patient/:
    $ref: ./paths/admin/patient-by-center-id.yaml
  /api/nurse/center/{centerId}/patient/:
    $ref: ./paths/nurse/patient-by-center-id.yaml
  /api/admin/patient/{patientId}:
    $ref: ./paths/admin/patient-by-id.yaml
  /api/nurse/patient/{patientId}:
    $ref: ./paths/nurse/patient-by-id.yaml
  /api/patient/patient/{patientId}:
    $ref: ./paths/patient/patient-by-id.yaml
  /api/admin/patient/{patientId}/statuses:
    $ref: ./paths/admin/statuses-by-patient-id.yaml
  /api/nurse/patient/{patientId}/statuses:
    $ref: ./paths/nurse/statuses-by-patient-id.yaml
  /api/patient/patient/{patientId}/statuses:
    $ref: ./paths/patient/statuses-by-patient-id.yaml
  /api/admin/status/{statusId}:
    $ref: ./paths/admin/status-by-id.yaml
  /api/nurse/status/{statusId}:
    $ref: ./paths/nurse/status-by-id.yaml
  /api/patient/status/{statusId}:
    $ref: ./paths/patient/status-by-id.yaml
components:
  schemas:
    $ref: "./schemas/index.yaml"
  securitySchemes:
    APIGatewayAuthorizer:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - "arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/COGNITO_USER_POOL_ID_TO_BE_REPLACED"
        identityValidationExpression: ".*"
tags:
  - name: Center
    description: 保健所に関するモデル
  - name: Nurse
    description: 観察者（保健師など）に関するモデル
  - name: Patient
    description: 療養者に関するモデル
  - name: Status
    description: 症状報告に関するモデル
  - name: CORS
    description: Cross-Origin Resource Sharing 設定
