type: object
properties:
  loginId:
    type: string
  password:
    type: string
  patientId:
    type: string
  centerId:
    type: string
  policy_accepted:
    type: string
    format: date-time
  phone:
    type: string
  display:
    type: boolean
