Resources:
  RPMAdminUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: RPMAdminUserPool
      Schema:
        - Name: email
          Required: true
          Mutable: true
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true

  AdminUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref RPMAdminUserPool
      Domain: ${self:provider.environment.AuthAdminUserPoolDomain}

  RPMAdminAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: RPMAdminAppClient
      UserPoolId: !Ref RPMAdminUserPool
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
      CallbackURLs:
        - "https://#{SwaggerDistribution.DomainName}"
      LogoutURLs:
        - "https://#{SwaggerDistribution.DomainName}"
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  RPMAdminIdentityProvider:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: RPMAdminIdentityPool
      CognitoIdentityProviders:
        - ProviderName: "cognito-idp.#{AWS::Region}.amazonaws.com/#{RPMAdminUserPool}"
          ClientId: !Ref RPMAdminAppClient
      AllowUnauthenticatedIdentities: false

  RPMAdminIdentityProviderRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref RPMAdminIdentityProvider
      Roles:
        authenticated: !GetAtt RPMAdminAuthRole.Arn

  RPMAdminAuthRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref RPMAdminIdentityProvider
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: api-gateway
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: apigateway:GET
                Resource: "arn:aws:apigateway:#{AWS::Region}::/restapis/#{ApiGatewayRestApi}/stages/${self:provider.stage}/exports/*"
  RPMAdminUser:
    Type: "AWS::Cognito::UserPoolUser"
    Properties:
      UserPoolId: !Ref RPMAdminUserPool
      UserAttributes:
        - Name: "email"
          Value: ${self:provider.environment.AdminUserEmail}
      Username: ${self:provider.environment.AdminUserName}

  RPMNurseUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: RPMNursePool
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: "admin_only"
            Priority: 1
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: false

  NurseUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref RPMNurseUserPool
      Domain: ${self:provider.environment.AuthNurseUserPoolDomain}

  RPMNurseAppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: RPMNurseAppClient
      UserPoolId: !Ref RPMNurseUserPool
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
      CallbackURLs:
        - "https://#{SwaggerDistribution.DomainName}"
      LogoutURLs:
        - "https://#{SwaggerDistribution.DomainName}"
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  RPMNurseIdentityProvider:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: RPMNurseIdentityPool
      CognitoIdentityProviders:
        - ProviderName: "cognito-idp.#{AWS::Region}.amazonaws.com/#{RPMNurseUserPool}"
          ClientId: !Ref RPMNurseAppClient
      AllowUnauthenticatedIdentities: false

  RPMNurseIdentityProviderRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref RPMNurseIdentityProvider
      Roles:
        authenticated: !GetAtt RPMNurseAuthRole.Arn

  RPMNurseAuthRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref RPMNurseIdentityProvider
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: api-gateway
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: apigateway:GET
                Resource: "arn:aws:apigateway:#{AWS::Region}::/restapis/#{ApiGatewayRestApi}/stages/${self:provider.stage}/exports/*"
