Resources:
  RemotePatientMonitoringCenterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RemotePatientMonitoringCenterTable-${self:provider.stage}
      KeySchema:
        - AttributeName: centerId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: centerId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
