Resources:
  GetCentersRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "GetCentersRole-${self:provider.stage}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: "/"
      Policies:
        - PolicyName: "GetCentersPolicy-${self:provider.stage}"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - dynamodb:Scan
                Resource:
                  - "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/RemotePatientMonitoringCenterTable-${self:provider.stage}"
                  - "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/RemotePatientMonitoringCenterTable-${self:provider.stage}/index/*"
  GetCenterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "GetCenterRole-${self:provider.stage}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: "/"
      Policies:
        - PolicyName: "GetCenterPolicy-${self:provider.stage}"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - dynamodb:Query
                  - dynamodb:GetItem
                Resource:
                  - "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/RemotePatientMonitoringCenterTable-${self:provider.stage}"
                  - "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/RemotePatientMonitoringCenterTable-${self:provider.stage}/index/*"
  PostCenterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "PostCenterRole-${self:provider.stage}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: "/"
      Policies:
        - PolicyName: "PostCenterPolicy-${self:provider.stage}"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - dynamodb:PutItem
                Resource:
                  - "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/RemotePatientMonitoringCenterTable-${self:provider.stage}"
  PutCenterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "PutCenterRole-${self:provider.stage}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: "/"
      Policies:
        - PolicyName: "PutCenterPolicy-${self:provider.stage}"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - dynamodb:UpdateItem
                Resource:
                  - "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/RemotePatientMonitoringCenterTable-${self:provider.stage}"
